name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  KATSU_PROJECT_ROOT: ${{ github.workspace }}

jobs:
  frontend-blazor:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore .Net dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  openssl-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup build cache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: build liboqs
      working-directory: ./liboqs
      run: |
        mkdir build && cd build
        cmake -GNinja -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/openssl/oqs" -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache ..
        ninja
        ninja install

    - name: build openssl
      working-directory: ./openssl
      run: |
        ./Configure no-shared linux-x86_64 -lm --prefix="${{ github.workspace }}/openssl-output"
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        make -j2
        make -j2 install_sw install_ssldirs
        ls -al "${{ github.workspace }}/openssl-output"

    - name: Archive openssl artifacts for linux
      uses: actions/upload-artifact@v3
      with:
        name: openssl-output-linux
        path: "${{ github.workspace }}/openssl-output"

  backend-flask-linux:
    runs-on: ubuntu-latest
    needs: openssl-linux
    defaults:
      run:
        working-directory: ./pykatsu
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v2
      with:
        name: openssl-output-linux
        path: openssl-output

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pipenv'
        cache-dependency-path: '**/Pipfile.lock'

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Restore Python dependecies
      run: |
        pipenv install --dev
        pipenv graph

    - name: Test Backend Flask
      run: |
        pipenv run python -m pytest

  backend-flask-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./pykatsu
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: shogo82148/actions-setup-perl@v1
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: win64
    - uses: ilammy/setup-nasm@v1
      with:
        platform: win64

    - name: build liboqs
      working-directory: .\liboqs
      run: |
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\openssl\oqs" ..
        ninja
        ninja install

    - name: build openssl
      working-directory: ./openssl
      run: |
        perl Configure no-makedepend VC-WIN64A
        nmake
        nmake install DESTDIR="${{ github.workspace }}\openssl-output"
        Get-ChildItem -Path "${{ github.workspace }}\openssl-output" -Recurse

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pipenv'
        cache-dependency-path: '**/Pipfile.lock'

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Restore Python dependecies
      run: |
        pipenv install --dev
        pipenv graph

    - name: Test Backend Flask
      run: |
        pipenv run python -m pytest

  backend-flask-mac:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./pykatsu
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup build cache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: build liboqs
      working-directory: ./liboqs
      run: |
        mkdir build && cd build
        cmake -GNinja -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/openssl/oqs" -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache ..
        ninja
        ninja install

    - name: build openssl
      working-directory: ./openssl
      run: |
        ./Configure no-shared darwin64-x86_64-cc -lm --prefix="${{ github.workspace }}/openssl-output"
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        make -j2
        make -j2 install_sw install_ssldirs
        ls -al "${{ github.workspace }}/openssl-output"

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pipenv'
        cache-dependency-path: '**/Pipfile.lock'

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Restore Python dependecies
      run: |
        pipenv install --dev
        pipenv graph

    - name: Test Backend Flask
      run: |
        pipenv run python -m pytest