on:
  release:
    types: [created]

name: Add Prebuild Blazor Frontend to Release
jobs:
  blazor-frontend-release-build:
    name: Build and Zip Blazor Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3

    - name: Publish Release Build
      run: dotnet publish -c Release -o ${{ github.workspace }}/frontend-blazor-output/

    - name: Zip Release Build
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: frontend-blazor.tar.gz
        path: frontend-blazor-output
        directory: ${{ github.workspace }}
        type: tar

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: ${{ github.workspace }}/frontend-blazor.zip
